FROM golang:1.13.7
ENV sourcesdir /go/src/github.com/microservices-demo/user/
ENV MONGO_HOST mytestdb:27017
ENV HATEAOS user
ENV USER_DATABASE mongodb

COPY . ${sourcesdir}
#RUN apk update
#RUN apk add git
#RUN go get github.com/derekparker/delve/cmd/dlv
RUN go get -v github.com/Masterminds/glide && cd ${sourcesdir} && glide install && go install
CMD sleep 10000
#ENTRYPOINT user
#EXPOSE 80
